<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter popup">
	    <div class="title">
		<strong><?php /* @escapeNotVerified */ echo __('Join our') ?></strong>
		<strong><?php /* @escapeNotVerified */ echo __('Tribe Newsletter!') ?></strong>
		<span class="free-book"><?php echo __("and get a FREE recipes book") ?></span>
	    </div>
	    <div class="content">
		<div class="page messages" id="news-message-popup" style="display: none;">
			<div class="messages">
				<div class="message message-error error" id="message-error-popup" style="display: none;">
					<div data-ui-id="checkout-cart-validationmessages-message-error" id="error-msg-popup">This email address is already subscribed.</div>
				</div>
				<div class="message message-success success" id="message-success-popup" style="display: none;">
					<div data-ui-id="checkout-cart-validationmessages-message-success" id="success-msg-popup">Thank you for your subscription.</div>
				</div>
			</div>
		</div>
		<form class="form subscribe" novalidate
		      method="post"
		      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
		      id="newsletter-validate-ajax">
		    <div class="field firstname">
		        <label class="label" for="firstname"><span><?php echo $block->escapeHtml(__('Full name')) ?></span></label>
		        <div class="control">
		            <input name="firstname" type="text" id="firstname" placeholder="<?php echo $block->escapeHtml(__('Full name')) ?>" data-validate="{required:true}"/>
		        </div>
		    </div>
		    <div class="field newsletter">
		        <label class="label" for="newsletter"><span><?php echo $block->escapeHtml(__('Email Address:')) ?></span></label>
		        <div class="control">
		            <input name="email" type="email" id="newsletter" placeholder="<?php echo $block->escapeHtml(__('Email Address')) ?>" data-validate="{required:true, 'validate-email':true}"/>
		        </div>
		    </div>
		    <div class="actions">
		        <button class="action subscribe primary" title="<?php echo $block->escapeHtml(__('Subscribe')) ?>" type="submit">
		            <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
		        </button>
		    </div>
		</form>
		<div class="unsubscribe-text"><?php echo __("You can unsubscribe at any time.") ?></div>
	    </div>
</div>
<script type="text/javascript">
require([ 'jquery', 'jquery/ui'], function($){
	var form = $('#newsletter-validate-ajax');
	form.submit(function(event) {
		event.preventDefault()
	   	if(form.validation('isValid')){
		    var customurl = '<?php echo $this->getUrl("newsletters/subscriber/new/"); ?>';	
		    $.ajax({
			    type : 'POST',
			    url : customurl,
			    data : jQuery('#newsletter-validate-ajax').serialize(),
			    success: function(msg){
				if(msg.status == "error"){
					$("#error-msg-popup").html(msg.msg);
					$("#message-success-popup").hide();
					$("#news-message-popup, #message-error-popup").show();
				}else{
					$("#success-msg-popup").html(msg.msg);
					$("#message-error-popup").hide();
					$("#news-message-popup, #message-success-popup").show();
				}
			    }
		    });
		}
	});
});
</script>
